### ISSUE TITLE
Extend to send a fedora message

### ISSUE THREAD

**Issue by ryanlerch** [GregSutcliffe/maubot-meetings#1]
Not sure how feasible this is to implement a plugin to a plugin, but the current fedora IRC meetbot sends a message to the Fedora Messaging bus for certain actions. (meeting start, end, actionitems, etc)

This was implemented in meetbot directly in our forked version (since meetbot was basically not under maintenance )

https://github.com/fedora-infra/supybot-meetbot/blob/develop/supybot_meetbot/meeting.py

However, it would be nice to be able to send these messages from the maubot-meetings plugin somehow if we can.

**Comment by GregSutcliffe** [comment]
I think we can pretty much copy that exact code from Supybot:
- Add the `send_fedora_messaging` config key (default False)
- Add a new `fedora.py` file to source at startup, if config is True
- Add the `sendfedoramessage` function from [Supybot](https://github.com/fedora-infra/supybot-meetbot/blob/1641f46b51475e5c7c0fc751911d2910787b874f/supybot_meetbot/meeting.py#L563)
- Use the same kind of `if`s as Supybot, eg [this one](https://github.com/fedora-infra/supybot-meetbot/blob/1641f46b51475e5c7c0fc751911d2910787b874f/supybot_meetbot/meeting.py#L334C1-L336C1)
```
  if self.config.send_fedora_messaging:
    self.sendfedoramessage("meeting.item.accepted", nick=nick, **kwargs)`
```

We can make `fedora_messaging` an option Pip dependency, and only load it if the config key is set. I think that should work?

**Comment by GregSutcliffe** [comment]
I like this approach, because it means we can implement multiple backends for storage, etc. While your deployment of this plugin would want to format and push the logs to https://meetbot.fedoraproject.org/, I would like to start pushing things like [this](https://meetbot.fedoraproject.org/ansible-community/2023-07-05/ansible_community_meeting.2023-07-05-18.00.log.html) to the Ansible forum. So we need configurable backends anyway.

**Comment by GregSutcliffe** [comment]
Took a shot at this today, I think I have the bare-bones of something working. @ryanlerch take a look at [this diff](https://github.com/GregSutcliffe/maubot-meetings/compare/main...backends) in the `backends` branch.

It definres a `fedora.py` and `ansible.py` and allows you to pick which in the plugin config file. You can see both define `log_msg` which is then called from the main bot in `(start|end)meeting`.

 My Python is ... not the best, so this might be a terrible way of going about this, but it seems to work. Here's a log snippet from my dev setup:
```
[2023-08-14 10:50:14,505] [INFO@maubot.instance.meetbot] Ansible: Starting
<snip matrix logs>
[2023-08-14 10:50:32,130] [INFO@maubot.instance.meetbot] Ansible: Ending
```

So long as the backend plugins all define the same messages, and we take care to factor common stuff up to the main plugin, I think this will do for now?

**Comment by ryanlerch** [comment]
going to close this one -- can do fedora messages with the backends system (its not done yet, but its possible)
