### ISSUE TITLE
Log replies in meeting logs

### ISSUE THREAD

**Issue by ryanlerch** [GregSutcliffe/maubot-meetings#20]
When a user replies (i.e evt.reply rather than evt.respond) directly to a message, it is not shown in the logs.

We should figure out how to display this, and how to log this, and how to display it in the output logs

**Comment by GregSutcliffe** [comment]
oh, that's a nasty bug, good catch.

**Comment by GregSutcliffe** [comment]
my hot-take is that it's enough to notice the message - logging/reporting it later would look like any other message. I don't think log-formats for threads are in scope at this point ;)

**Comment by GregSutcliffe** [comment]
Hmm, I can't replicate this, at least with my branch on #22. Here's the room view:

![2023-09-13-142115_373x523_scrot](https://github.com/GregSutcliffe/maubot-meetings/assets/827786/50c04403-bebb-4738-b61c-7e99c84b0f8d)

And here's the SQlite db right before the !em wiped it:

timestamp | sender | message | tag | topic
-- | -- | -- | -- | --
1694611318750 | @standup:emeraldreverie.org | Meeting started at 2023-09-13 13:21:58 UTC |   |  
1694611318750 | @standup:emeraldreverie.org | The Meeting name is 'Meeting Test' |   |  
1694611318750 | @gwmngilfen:ansible.im | !sm |   |  
 1694611324813 | @gwmngilfen:ansible.im | hello |   |  
 1694611330531 | @gwmngilfen:ansible.im | a reply! |   |  
 1694611345678 | @gwmngilfen:ansible.im | an ^action reply | action |  

The parsed logs are fine too, as you would expect.

**Comment by ryanlerch** [comment]
turns out it was because bot messages default to NOTICE when sending, and by default the passive action doesn't look for em, only TEXTs. anyhoo #23 fixes this.

**Comment by GregSutcliffe** [comment]
I think we can close this as done in https://github.com/GregSutcliffe/maubot-meetings/releases/tag/0.3.0 right?
