### ISSUE TITLE
Improve the Fedora Messaging messages we send out

### ISSUE THREAD

**Issue by ryanlerch** [GregSutcliffe/maubot-meetings#21]
Currently, we only send out a very basic Fedora Messaging message with the bare minimum for mote to do its thing.

we really need to expand this out with information close to if not identical to what the current supybot-fedora fork sends out for end meeting.

we also need to send messages on start meeting.

note too that the current meetbot sends messages for topics and most other actions, but going to drop that going forward

**Comment by GregSutcliffe** [comment]
Yeah, I think reactions are a sufficient way to indicate the bot got the command. I'm hoping to move topic and meetingname to !commands today - we tried the current version in docs yesterday and the `@passive` commands made quite a mess
