### ISSUE TITLE
Meeting Names

### ISSUE THREAD

**Issue by ryanlerch** [GregSutcliffe/maubot-meetings#4]
Because the majority of fedora meetings tend to happen in #fedora-meeting{-1,2,3,4,5,23454} our supybot-meetbot was patched to require a meeting name when starting a meeting. 

There was also a command 'meetingname' to change the meeting name, and this was used for naming logs etc.

So i suggest we:

* add meetingname as an optional parameter to "startmeeting"
* add a new command ^meetingname to set / change the meeting name -- sometimes a user types the wrong meeting name and wants to change it
* add a new config option to require a meetingname to be set before !endmeeting is processed

the config option is kind of required for fedora-land as trying to autogen meeting names will just result in a bunch of "fedora-meeting-meetings" which is not helpful

**Comment by ryanlerch** [comment]
@GregSutcliffe pls assign this to me :) this is more of a to-do for me

**Comment by GregSutcliffe** [comment]
Done. But I might work on it if I get there first, this would also be useful to other communities. As Neal said on Pagure, I can see this being useful to more than just Ansible & Fedora, so we should keep that in mind ;)

**Comment by ryanlerch** [comment]
oh sorry! i wasnt implying that this should be just for the Fedora backend -- was just trying to give some background on why i think we need the feature :)
