### ISSUE TITLE
Make `!help` a working command and the default, make `!halp` an alias

### ISSUE THREAD

**Issue by justwheel** [GregSutcliffe/maubot-meetings#41]
If someone needs to call out for help on a task or an issue, the only valid alias is `!halp`. It is novel, but that is also not English and the novelty is not always understood. Non-English speakers will not always understand this. Making `!help` both a working command and also the default makes more sense, while `!halp` can be an "easter egg" for those who prefer to write it that way.

**Comment by gotmax23** [comment]
`!help` would conflict with zodbot

**Comment by ryanlerch** [comment]
@jwflory also, !halp is one of the "tags" (action, link, etc) which basically just tag that message with that tag.

the good news is that these tags are configurable -- so if we want to change it for fedora meetbot (in fedora land) we can!

the bad news is zodbot already uses !help

Going to close this one here and we can re-open over at https://github.com/fedora-infra/matrix-bots if we want to change the config for the fedora meetbot instance
