### ISSUE TITLE
Emit Fedora Messages for some actions

### ISSUE THREAD

**Issue by ryanlerch** [GregSutcliffe/maubot-meetings#7]
Currently the Fedora meetbot fork https://github.com/fedora-infra/supybot-meetbot/ sends Fedora Messages for certain things.

I need to implement this in the Fedora Backend here on meetings.

**Comment by GregSutcliffe** [comment]
All code in the Fedora backend is all yours! Happy to review if you want, but feel free to merge as needed :)
